### ISSUE TITLE
cannot send DM

### ISSUE THREAD

**Issue by shokai** [shokai/tw#61]
```
% tw -v
tw version 1.0.8
% ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.0.0]
```
### sending DM fail

```
% tw -dm:to=shokai test
```

```
/Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/client/auth.rb:4:in `client': uninitialized class variable @@client in Tw::Client (NameError)
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/conf.rb:74:in `update_twitter_config'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/client/helper.rb:9:in `char_length_with_t_co'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/app/cmds.rb:57:in `block in regist_cmds'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/app/main.rb:119:in `call'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/app/main.rb:119:in `block in run'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/app/main.rb:117:in `each'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/lib/tw/app/main.rb:117:in `run'
    from /Users/sho/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tw-1.0.8/bin/tw:9:in `<top (required)>'
    from /Users/sho/.rbenv/versions/2.0.0-p353/bin/tw:23:in `load'
    from /Users/sho/.rbenv/versions/2.0.0-p353/bin/tw:23:in `<main>'
```

**Comment by misshie** [comment]
インストール直後に、一度も通常のTweetをせずに、いきなりDMを送信しようとすると、同じエラーが再現できました。一旦、通常のTweetをすると、以後エラーはでません。
