### ISSUE TITLE
hang up in searching after searched some keywords

### ISSUE THREAD

**Issue by milligramme** [shokai/tw#65]
起動後2，3回検索を実行するとtwが応答しなくなります

```
% tw -s=ruby
^C/Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `connect': Interrupt
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/net/http.rb:1126:in `get'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/request/multipart.rb:14:in `call'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/request.rb:33:in `perform'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/search_results.rb:52:in `fetch_next_page'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/enumerable.rb:13:in `each'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/enumerable.rb:14:in `each'
	from /Users/gdansk/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/enumerable.rb:14:in `each'
	from /Users/gdansk/fork/tw/lib/tw/client/request.rb:16:in `map'
	from /Users/gdansk/fork/tw/lib/tw/client/request.rb:16:in `search'
	from /Users/gdansk/fork/tw/lib/tw/app/cmds.rb:146:in `block in regist_cmds'
	from /Users/gdansk/fork/tw/lib/tw/app/main.rb:119:in `call'
	from /Users/gdansk/fork/tw/lib/tw/app/main.rb:119:in `block in run'
	from /Users/gdansk/fork/tw/lib/tw/app/main.rb:117:in `each'
	from /Users/gdansk/fork/tw/lib/tw/app/main.rb:117:in `run'
	from /Users/gdansk/fork/tw/bin/tw:9:in `<main>'
```

**Comment by shokai** [comment]
治りました
