### ISSUE TITLE
-dm:to not work

### ISSUE THREAD

**Issue by shokai** [shokai/tw#69]
% tw -dm:to=shokai_log hello

```
/usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/client/auth.rb:4:in `client': uninitialized class variable @@client in Tw::Client (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/conf.rb:74:in `update_twitter_config'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/client/helper.rb:9:in `char_length_with_t_co'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/app/cmds.rb:57:in `block in regist_cmds'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/app/main.rb:119:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/app/main.rb:119:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/app/main.rb:117:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/lib/tw/app/main.rb:117:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/tw-1.0.11/bin/tw:9:in `<top (required)>'
	from /usr/local/bin/tw:23:in `load'
	from /usr/local/bin/tw:23:in `<main>'
```

**Comment by misshie** [comment]
インストール直後に、一度も通常のTweetをせずにDMを送信しようとすると、同じエラーが再現できました。

一旦、通常のTweetをしてからDMを送信すればそれ以降エラーはでません。

（closedの https://github.com/shokai/tw/issues/61 にコメントしてしまったので、再投稿します）
